sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
cache:
  directories:
    - "node_modules"
env:
  global:
    - BUILD_TIMEOUT=10000
install: npm install
script: npm run build
dist: trusty
